### ISSUE TITLE
Improve usage detection.

### ISSUE THREAD

**Issue by davidlehn** [digitalbazaar/firefox-iframe-getcomputedstyle#1]
The simple check for user-agent "firefox" string is rather basic.  Should consider more generic test for browsers that might need this code either with better user-agent detection or run a quick code based check.

Maybe all gecko based browsers need this?
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent/Firefox

**Comment by dlongley** [comment]
Closing -- this repo will be archived in the near future. This was only needed for Firefox <= 62 which is quite old now.
